apiVersion: v1
kind: Pod
metadata:
  name: al2023
spec:
  containers:
  - name: al2023
    image: public.ecr.aws/amazonlinux/amazonlinux:2023
    command:
      - "sh"
      - "-c"
      - "sleep infinity"
