apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector: # このセレクタに指定したラベルにマッチする Pod に Service へのアクセスが割り振られます
    component: my-permission-pod
  ports:
  - protocol: TCP # このポートの IP プロトコル
    port: 8080 # このサービスによって公開されるポート
    targetPort: 80 # サービスの対象となるポッドでアクセスするポートの番号または名前。
---
apiVersion: v1
kind: Pod
metadata:
  name: my-permission-pod
  labels:
    component: my-permission-pod
spec:
  initContainers:
    - name: init
      image: alpine:3.9
      command:
        - "sh"
        - "-c"
        - "date >> /mount1/init.txt"
      volumeMounts:
        - name: myvol
          mountPath: /mount1
  containers:
    - image: nginx
      name: web
      ports:
        - containerPort: 80
      volumeMounts:
        - name: myvol
          mountPath: /mount2
  volumes:
  - name : myvol
    emptyDir: {}
